# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scattergun_coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundreport',
            name='a_defense',
            field=models.TextField(blank=True, choices=[('Portcullis', 'Portcullis'), ('Cheval de Frise', 'Cheval de Frise'), ('Ramparts', 'Ramparts'), ('Moats', 'Moats'), ('Drawbridge', 'Drawbridge'), ('Sally Port', 'Sally Port'), ('Rock Wall', 'Rock Wall'), ('Rough Terrain', 'Rough Terrain')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='roundreport',
            name='a_defense_ability',
            field=models.IntegerField(blank=True, choices=[(0, 'Inapplicable/Unknown/Does not work'), (1, 'Terrible'), (2, 'Bad'), (3, 'OK, I guess...'), (4, 'Good'), (5, 'Fantastic')], null=True),
        ),
        migrations.AddField(
            model_name='roundreport',
            name='b_defense',
            field=models.TextField(blank=True, choices=[('Portcullis', 'Portcullis'), ('Cheval de Frise', 'Cheval de Frise'), ('Ramparts', 'Ramparts'), ('Moats', 'Moats'), ('Drawbridge', 'Drawbridge'), ('Sally Port', 'Sally Port'), ('Rock Wall', 'Rock Wall'), ('Rough Terrain', 'Rough Terrain')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='roundreport',
            name='b_defense_ability',
            field=models.IntegerField(blank=True, choices=[(0, 'Inapplicable/Unknown/Does not work'), (1, 'Terrible'), (2, 'Bad'), (3, 'OK, I guess...'), (4, 'Good'), (5, 'Fantastic')], null=True),
        ),
        migrations.AddField(
            model_name='roundreport',
            name='c_defense',
            field=models.TextField(blank=True, choices=[('Portcullis', 'Portcullis'), ('Cheval de Frise', 'Cheval de Frise'), ('Ramparts', 'Ramparts'), ('Moats', 'Moats'), ('Drawbridge', 'Drawbridge'), ('Sally Port', 'Sally Port'), ('Rock Wall', 'Rock Wall'), ('Rough Terrain', 'Rough Terrain')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='roundreport',
            name='c_defense_ability',
            field=models.IntegerField(blank=True, choices=[(0, 'Inapplicable/Unknown/Does not work'), (1, 'Terrible'), (2, 'Bad'), (3, 'OK, I guess...'), (4, 'Good'), (5, 'Fantastic')], null=True),
        ),
        migrations.AddField(
            model_name='roundreport',
            name='d_defense',
            field=models.TextField(blank=True, choices=[('Portcullis', 'Portcullis'), ('Cheval de Frise', 'Cheval de Frise'), ('Ramparts', 'Ramparts'), ('Moats', 'Moats'), ('Drawbridge', 'Drawbridge'), ('Sally Port', 'Sally Port'), ('Rock Wall', 'Rock Wall'), ('Rough Terrain', 'Rough Terrain')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='roundreport',
            name='d_defense_ability',
            field=models.IntegerField(blank=True, choices=[(0, 'Inapplicable/Unknown/Does not work'), (1, 'Terrible'), (2, 'Bad'), (3, 'OK, I guess...'), (4, 'Good'), (5, 'Fantastic')], null=True),
        ),
    ]
