# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scattergun_coreapp', '0002_auto_20160311_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundreport',
            name='a_defense',
            field=models.CharField(blank=True, choices=[('Portcullis', 'Portcullis'), ('Cheval de Frise', 'Cheval de Frise'), ('Ramparts', 'Ramparts'), ('Moats', 'Moats'), ('Drawbridge', 'Drawbridge'), ('Sally Port', 'Sally Port'), ('Rock Wall', 'Rock Wall'), ('Rough Terrain', 'Rough Terrain')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='roundreport',
            name='b_defense',
            field=models.CharField(blank=True, choices=[('Portcullis', 'Portcullis'), ('Cheval de Frise', 'Cheval de Frise'), ('Ramparts', 'Ramparts'), ('Moats', 'Moats'), ('Drawbridge', 'Drawbridge'), ('Sally Port', 'Sally Port'), ('Rock Wall', 'Rock Wall'), ('Rough Terrain', 'Rough Terrain')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='roundreport',
            name='c_defense',
            field=models.CharField(blank=True, choices=[('Portcullis', 'Portcullis'), ('Cheval de Frise', 'Cheval de Frise'), ('Ramparts', 'Ramparts'), ('Moats', 'Moats'), ('Drawbridge', 'Drawbridge'), ('Sally Port', 'Sally Port'), ('Rock Wall', 'Rock Wall'), ('Rough Terrain', 'Rough Terrain')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='roundreport',
            name='d_defense',
            field=models.CharField(blank=True, choices=[('Portcullis', 'Portcullis'), ('Cheval de Frise', 'Cheval de Frise'), ('Ramparts', 'Ramparts'), ('Moats', 'Moats'), ('Drawbridge', 'Drawbridge'), ('Sally Port', 'Sally Port'), ('Rock Wall', 'Rock Wall'), ('Rough Terrain', 'Rough Terrain')], max_length=15, null=True),
        ),
    ]
